export { default as logo} from "./IP-Logo-Hori.86db063b.png"
export { default as logo1} from "./Artboard 6 copy.png"
export { default as slider1} from "./pattern-bg-1.jpg"
export { default as slider2} from "./1692011648348.gif"
export { default as slider3} from "./h3-bg-shape-earth.webp"
export { default as slider4} from "./footer-3-bg.webp"
export { default as img1} from "./a2-img-1.webp"
export { default as img2} from "./a2-img-3.webp"
export { default as img3} from "./a2-img-2.webp"
export { default as img4} from "./s3-bg-1.webp"
export { default as web} from "./360_F_214879686_R3HFJlk6WLr1kcdvy6Q9rtNASKN0BZBS.jpg"
export { default as app} from "./representation-user-experience-interface-design-smartphone_23-2150165977.jpg"
export { default as social} from "./Custom-software-development.jpg"
export { default as cloud} from "./A-Guide-to-Cloud-Cost-Optimization.jpg"
export { default as custom} from "./240_F_419269782_9LsP3TQndMVnZ2j3ZhTPhMjaqQpFAth9.jpg"
export { default as uiux} from "./gradient-ui-ux-elements-background_23-2149056159.jpg"
export { default as img5} from "./Unknown.000dbb23.jpeg"
export { default as img6} from "./ch3-img-1.webp"
export { default as img7} from "./ch3-il-2.webp"
export { default as img8} from "./illustration-1.png"

export { default as img9} from "./cheerful-indian-man.jpg"
export { default as img10} from "./content-successful-male-manager-using-tablet-looking-camera.jpg"
export { default as img11} from "./portrait-smiling-businesswoman-with-mobile-phone.jpg"
